pdf:
	xelatex 2021-08-25-Data_Visualisation_Summer_school_Data_Literacy_in_Health.tex

pdf_follow_changes:
	latexmk -xelatex -pvc 2021-08-25-Data_Visualisation_Summer_school_Data_Literacy_in_Health.tex

clean:
	rm -f *aux *log *nav *snm *out *toc *pdf *.fdb_latexmk *.fls *~
